copy StringTableEnglish.txt StringTableChinese.txt
copy StringTableEnglish.txt StringTableCzech.txt
copy StringTableEnglish.txt StringTableDanish.txt
copy StringTableEnglish.txt StringTableDutch.txt
copy StringTableEnglish.txt StringTableEnglish.txt
copy StringTableEnglish.txt StringTableFinnish.txt
copy StringTableEnglish.txt StringTableFrench.txt
copy StringTableEnglish.txt StringTableGerman.txt
copy StringTableEnglish.txt StringTableGreek.txt
copy StringTableEnglish.txt StringTableHungarian.txt
copy StringTableEnglish.txt StringTableItalian.txt
copy StringTableEnglish.txt StringTableJapanese.txt
copy StringTableEnglish.txt StringTableKorean.txt
copy StringTableEnglish.txt StringTableNorwegian.txt
copy StringTableEnglish.txt StringTablePolish.txt
copy StringTableEnglish.txt StringTablePortugueseBrazilian.txt
copy StringTableEnglish.txt StringTablePortugueseStandard.txt
copy StringTableEnglish.txt StringTableRussian.txt
copy StringTableEnglish.txt StringTableSpanishMexican.txt
copy StringTableEnglish.txt StringTableSpanishStandard.txt
copy StringTableEnglish.txt StringTableSwedish.txt
copy StringTableEnglish.txt StringTableTaiwanese.txt
copy StringTableEnglish.txt StringTableThai.txt